import numpy as np
a = np.array([[1],[2]])
a = a.reshape(1,-1)
print(a.shape)
a = np.squeeze(a)
print(a.shape)
b  =  np.array([1,2])
c = np.array([[3,4],[5,6]])
print(b.dot(c))
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a.dot(b))
